import 'dart:convert';

void main(List<String> args) {
  const String json = ''' 
            {
                "_identifier": "23000",
                "_entityName": "Lds_Enquiryform",
                "ref": "Lds_Enquiryform/FFFF8D31C062483B863B662A3A939D4A",
                "id": "FFFF8D31C062483B863B662A3A939D4A",
                "client": "D1B565840F95464DA296746768738853",
                "client\$_identifier": "Sairoshini",
                "organization": "177D7D9FA9994A80B92C70D9734BB68B",
                "organization\$_identifier": "Sai Roshini Capital Pvt. Ltd. - Sai Roshini Capital Pvt. Ltd.",
                "active": true,
                "creationDate": "2023-01-14T16:41:28+05:30",
                "createdBy": "FF667953CE4E489FAEA8B564D5E2B1EE",
                "createdBy\$_identifier": "vamshik",
                "updated": "2023-02-02T10:46:48+05:30",
                "updatedBy": "3FFE2DCB9374432E83A4D161B968367D",
                "updatedBy\$_identifier": "mohan",
                "customername": "PREMKUMAR S",
                "mobilenumber": "6309978336",
                "location": "D81542C540ED43D48A9620A58BDB3AF0",
                "location\$_identifier": "10 & 11,G1 Srinidhi apartment Perumal Kovil West mada street - West Saidapet NEAR Jayaraj theatre - 600015 -  - Tamilnadu - India - CHENNAI",
                "dateofbirth": "2001-12-14",
                "prooftypenumber": "684969489535",
                "firstduedate": "2023-02-05",
                "model": null,
                "productvalue": 23000,
                "emiamount": 2875,
                "mindownpayment": 0,
                "downpaymentcollected": 590,
                "loanamount": 23000,
                "processingfee": 0,
                "loanpreapproved": true,
                "customercomments": "DIGITAL PROCESSS COMPLETED",
                "loandisburse": true,
                "disburse": true,
                "lDSProoftype": "44E2956938B74346A5CEBDD018032ACA",
                "lDSProoftype\$_identifier": "PAN Card",
                "loanno": "EZF94677",
                "alternatenumber": "6309978336",
                "status": "CO",
                "expirydate": null,
                "preapprove": true,
                "rejectreason": null,
                "cibilscore": 734,
                "loanrejected": false,
                "panno": "FQCPP7167J",
                "nameonpan": "PREMKUMAR S",
                "lDSProofofadd": "44E2956938B74346A5CEBDD018032ACA",
                "lDSProofofadd\$_identifier": "PAN Card",
                "isuploaded": false,
                "uploaddocument": false,
                "residentialstatus": "RI",
                "loanstatus": "Standard",
                "occupationtype": "SPS",
                "fathername": "SARAVANAN",
                "mothername": " HEMAVATHI",
                "gender": "M",
                "maritalstatus": "Unmarried",
                "emailid": "testezfinanz+PF-QA-customer@gmail.com",
                "bankname": "0D4F0B2372884AACA0359226CF858828",
                "bankname\$_identifier": "BANK OF BARODA",
                "bankbranch": "SAIDAPET,CHENNAI ,TN",
                "ifsccode": "BARB0SAIDAP",
                "accountno": "44830100001960",
                "paymentmethod": "97AEC07BE4744F56A8F778EB9AE111B6",
                "paymentmethod\$_identifier": "ACH",
                "shiptoaddress": "KOLORS-TNAGAR,CHENNAI",
                "annualincome": 200000,
                "product": "HEALTH CARE",
                "accounttype": "Saving",
                "tenure": 8,
                "lDSAgent": "677FCC6A3FD54ACEBFA7464644F4E3E6",
                "lDSAgent\$_identifier": "KOLORS HEALTHCARE LLP - 8/0 EMI PLAN",
                "intrestratetype": "Flat Rate",
                "advemi": 0,
                "anuintrate": 0,
                "customercode": "SRRSEZF94677",
                "agentbranch": "146FB4A8D6D641EF918D53929D26BA1F",
                "agentbranch\$_identifier": "TNAGAR - CHENNAI",
                "branchinvoiceno": "--",
                "aadharlink": false,
                "bpartner": "6AF9B04FD7E44DFFB7FEF33E884E08A4",
                "bpartner\$_identifier": "PREMKUMAR S_EZF94677 - ",
                "bpagent": "4B4C4128E4624577B0C90D9E7EC24C82",
                "bpagent\$_identifier": "KOLORS HEALTHCARE LLP - ",
                "docchargesgst": 590,
                "processchargegst": 0,
                "interesttenure": null,
                "createmandate": true,
                "sendtoesign": true,
                "enachstatus": "register_success",
                "enacherror": null,
                "downloadmandate": true,
                "mandateid": "ENA230114164151209QU7318E7463TAP",
                "url": "https://app.digio.in/#/gateway/login/ENA230114164151209QU7318E7463TAP/TSE200120123202441ATC66LAU26978R/8668044123",
                "downloadmandateurl": null,
                "ownertype": "1",
                "lDSOwner": null,
                "lDSLoanaccounttype": "9EDB94ED03F5406D930668019AA63EC5",
                "lDSLoanaccounttype\$_identifier": "Consumer Loan - 06",
                "asset": "01",
                "highsanctionedamount": 500,
                "overdueamount": 0,
                "currentbalance": 0,
                "noofenquiries": 0,
                "sanctionLetter": false,
                "insuranceCharges": 0,
                "otherCharges": 0,
                "groupinsurance": 0,
                "actualdownpayment": null,
                "ispersonalloan": false,
                "lDSInsurer": null,
                "employername": null,
                "designation": null,
                "employeraddress": null,
                "officephonenumber": null,
                "umrnnumber": "BARB7021401230014196",
                "generateLoanApplication": true,
                "esigndocumentid": "DID230114170109544328BJCURMQPAHS",
                "officialEmail": null,
                "esignlink": true,
                "esignurl": "https://app.digio.in/#/gateway/login/DID230114170109544328BJCURMQPAHS/8668044123/8668044123",
                "downloadSignedDocument": false,
                "mindownpaymentrate": null,
                "esignidentityname": "Premkumar",
                "esignidentityaadhaar": "9535",
                "esignidentitygender": "M",
                "esignidentitydateofbirth": "2023-01-14",
                "esignidentityyearofbirth": 2001,
                "getdetails": true,
                "approveesign": true,
                "esignstatus": "Approved",
                "enachspb": "Yes Bank Ltd",
                "enachstage": "auth_success",
                "ecsapplicable": true,
                "ecsamount": 23000,
                "enachstagecheck": true,
                "sponserbank": "07F0E1919212423797A699EAC535BD79",
                "sponserbank\$_identifier": "YES BANK",
                "esignguridentityname": null,
                "esignguridentityaadhaar": null,
                "esignguridentitygender": null,
                "esignguridentityyearofbirth": null,
                "esigngurstatus": null,
                "esignguridentitydateofbirth": null,
                "esigngurdocumentid": null,
                "esigngururl": null,
                "enachgurstatus": null,
                "enachgurerror": null,
                "gurmandateid": null,
                "gururl": null,
                "gurecsamount": null,
                "gurecsapplicable": false,
                "enachgurstage": null,
                "enachgurspb": null,
                "gurumrnnumber": null,
                "createGuarantorMandate": false,
                "checkGuarantorMandateStage": false,
                "guarantormandateurl": false,
                "downloadguarantormandate": false,
                "creditlimit": null,
                "vkycrefno": "B169B6A9890848888CA0B76E66A60FB3",
                "vkycrefno\$_identifier": "EZCUST1266568",
                "manualapprove": false,
                "commentonmanualapp": null,
                "applicationprocessed": "CD",
                "manualappbtn": false,
                "currentaddress": "D81542C540ED43D48A9620A58BDB3AF0",
                "currentaddress\$_identifier": "10 & 11,G1 Srinidhi apartment Perumal Kovil West mada street - West Saidapet NEAR Jayaraj theatre - 600015 -  - Tamilnadu - India - CHENNAI",
                "iscurrentadd": true,
                "lDSDoSenton": "2023-01-14",
                "lDSDoSentby": "FF667953CE4E489FAEA8B564D5E2B1EE",
                "lDSDoSentby\$_identifier": "vamshik",
                "micr": 600012056,
                "employeeaddress": null,
                "mandatetype": "E",
                "mandateregisteredon": null,
                "callverificationdoneby": "FF667953CE4E489FAEA8B564D5E2B1EE",
                "callverificationdoneby\$_identifier": "vamshik",
                "iscallverificationdone": true,
                "callverification": true,
                "lDSBankdetails": "489BC2B99E0A4BCC821EFAD6D364B8E8",
                "lDSBankdetails\$_identifier": "BANK OF BARODA",
                "validated": true,
                "bankvalidationBy": "07E779C5AFBA4BEC8F718E0217BC6E70",
                "bankvalidationBy\$_identifier": "sidhartha",
                "bavalidation": false,
                "getupimandatestatus": false,
                "createupimandate": false,
                "downpaymentcollectionmode": null,
                "initiatedownpayment": false,
                "upimandateerror": null,
                "upimandateapplicable": false,
                "uPIMandateRegisteredAmount": null,
                "uPIMandateurl": null,
                "verifiedUpiMandates": null,
                "upimandateTokenStatus": null,
                "uPIMandateToken": null,
                "uPISponserbank": null,
                "uPIMandateOrder": null,
                "uPIMandateCustomer": null,
                "upimandatestatus": null,
                "upimandateregisteredon": null,
                "effectiveinterestrate": 2.529999999999999804600747665972448885440826416015625,
                "isdownpaymentcollected": false,
                "downpaymentstatus": null,
                "downpaymenturl": null,
                "ezmsAadharno": "684969489535",
                "upimandateloanno": null,
                "upimandatereinitiated": false,
                "downpaymentOrderid": null,
                "upipaymentid": null,
                "downpaymentpaymentid": null,
                "regenerateLinks": null,
                "isapproveemailsent": false,
                "isapprovesmssent": false,
                "ldsMandates": null,
                "call": null,
                "downcallrecording": null,
                "callrecStarttime": null,
                "downpaymentinititatedby": null,
                "downpaymentinititatedate": null,
                "downpaymentcollectedat": null,
                "callverfRequestedAt": null,
                "callverfRequestedby": null,
                "emandateAccesstoken": null,
                "esignAccesstoken": null,
                "esignaccesstokenGeneratedat": null,
                "esignaccesstokenValidtill": null,
                "ldsDownpayment": null,
                "givenAt": null,
                "givenBy": null,
                "requestedAt": null,
                "requestedBy": null,
                "requestedReason": null,
                "mandateacctokenGenat": null,
                "mandateacctokenValidtill": null,
                "manualapprovalStatus": null,
                "recordTime": 1708416039876
            }
''';

  final decodedJson = jsonDecode(json) as Map;
  print(decodedJson.keys.toList().map((e) => "'$e' \n ").toList());
}
